# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty
#relative_permalinks: true

# Setup
title:               cnabro
tagline:             'dev blog'
description:         'cnabro91@gmail.com'
url:                 http://cnabro.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              cnabro
  url:               https://cnabro.github.io
  email:             cnabro91@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
